### ISSUE TITLE
Dropping item in main hand while trying to drop an item in inventory.

### ISSUE THREAD

**Issue by dreckz** [PieKing1215/InvMove-Forge#1]
**Describe the bug**
While in inventory, you normally can press [Q] while hovering over an item with your cursor.  This means that the item hovered over will drop.  However, instead, while that specific item may drop, so does the item that is in your main hand.  Players on my server found this very annoying and would run into problems like dropping their main hand pickaxe into lava when just throwing out junk.

**To Reproduce**
Hold an item in your main hand, open inventory, and press [Q] over a different item in your inventory.

**Version and Mod List**
List the version of InvMove and the version of Forge the issue happens on.
Invmove: 0.4.0
Forge: 31.2.28

List any other mods being used.
If possible, try to reproduce the bug with the smallest number of other mods you can. This can help me figure out where the problem occurs.

**Comment by PieKing1215** [comment]
Hey thanks for reporting this!

I'm trying to reproduce this but I can't get it to happen so I have some questions:

Does it only happen sometimes or does it always drop your main hand item when you hit [Q] on an itemstack?
Does it only happen on multiplayer or does it happen in singleplayer too?
Does it only happen in certain inventories?
Are you actually using any other mods? (if so, I will add compatibility for whatever is conflicting)

(for reference I tried to reproduce on single and multiplayer with v0.4.0 on Forge 31.2.28 and I couldn't get it to happen)

**Comment by dreckz** [comment]
It always happens on both SP and MP in inventory.  I AM using other mods in an unlisted modpack I'm in current developments for.  To see the mod list you can import the modpack from the dropbox link containing the image below:
https://www.dropbox.com/home/RoA%20Versions/BEta/ROAB5_6_2

**Comment by PieKing1215** [comment]
I can't access the folder
You need to do share->create link and dropbox should make a view-only link so I can see the files

**Comment by dreckz** [comment]
Try this link:
https://www.dropbox.com/sh/yebrt4ppsqab557/AADcX7VM4SfeMxYoq7ts6icoa?dl=0

**Comment by PieKing1215** [comment]
Yeah that link worked 👍 
There was a conflict with ItemPhysic's custom drop behavior and it should be fixed in [InvMove 0.4.1](https://github.com/PieKing1215/InvMove/releases/tag/v0.4.1) (also updated on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/invmove/files/3001856))
