### ISSUE TITLE
Crouching in horses inventory cause you to dismount

### ISSUE THREAD

**Issue by juraj-hrivnak** [PieKing1215/InvMove-Forge#10]
**Describe the bug**
Crouching in horses inventory cause you to dismount, though the crouching in GUIs is disabled in the config.

**To Reproduce**
Tame a horse, add a saddle and crouch while being in the inventory.

**Version and Mod List**
InvMove: 0.4.6
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Comment by PieKing1215** [comment]
Ported "Allow dismount" option (previously only on Fabric) in the rewrite: [v0.5.0](https://github.com/PieKing1215/InvMove/releases/tag/v0.5.0)
Rewrite repo: https://github.com/PieKing1215/InvMove
(note: 1.18+ only, I might do a small bug fix backport but not yet)
