### ISSUE TITLE
[Mod Incompatibility] Moving while in the lock picking screen on the 

### ISSUE THREAD

**Issue by dreckz** [PieKing1215/InvMove-Forge#3]
**Describe the bug**
While attempting to use the lockpicking mod on the lockpick screen (Lock Mod), I am not able to do it properly because I continue to move while attempting to lockpick
**To Reproduce**
Download the Lock mod: https://www.curseforge.com/minecraft/mc-mods/locks
Attempt to pick a lock

**Screenshots**
![image](https://user-images.githubusercontent.com/59788491/88245981-ab3b3e00-cc5e-11ea-93ae-9450db191387.png)

**Version and Mod List**
List the version of InvMove and the version of Forge the issue happens on:
InvMove: 0.4.3
Forge: 31.2.31

List any other mods being used (other than Cloth Config):

-Locks Mod:
https://www.curseforge.com/minecraft/mc-mods/locks

**Comment by PieKing1215** [comment]
I'll add a compatibility for it in the next update.
In the meantime, you should be able to disable movement in this GUI by going to ```Main Menu->Mods->InvMove->Config->UI Movement``` and open the "unrecognized" category and try to find one that has something to do with the lock pick mod.

**Comment by PieKing1215** [comment]
Added compatibility in [v0.4.4](https://github.com/PieKing1215/InvMove/releases/tag/v0.4.4)
