### ISSUE TITLE
Support of your mod InvMove with the FreeCamera Mod from Modbuilder: KaptainWutax

### ISSUE THREAD

**Issue by Titoo8899** [PieKing1215/InvMove-Forge#4]
Link of the Mod "FreeCamera": https://www.curseforge.com/minecraft/mc-mods/freecamera

Hi,
the Problem is then I play with your Mod and the FreeCamera Mod work the FreeCamera Mod not to 100%. The FreeCamera Mod is a Mod with Smoother Camera Drive then I walk or Run in a world. But then I open a Inventory and Walk left the Inventory was on is the Camera not Drive with the Person. I show then the Inventory on is in one Direction. I hope you can the Support of your mod and this FreeCamera Mod make in next time for 1.12.2. 

![2020-07-24_17 52 33](https://user-images.githubusercontent.com/42325138/88410390-a00b1e00-cdd6-11ea-86ff-106bcc0e39e1.png)
![2020-07-24_17 52 34](https://user-images.githubusercontent.com/42325138/88410395-a0a3b480-cdd6-11ea-8460-ea8dff1d51ee.png)
![2020-07-24_17 52 35](https://user-images.githubusercontent.com/42325138/88410396-a13c4b00-cdd6-11ea-84a0-49294cf458ee.png)
![2020-07-24_17 52 36](https://user-images.githubusercontent.com/42325138/88410405-a4cfd200-cdd6-11ea-8ba5-4ec8576f3504.png)
![2020-07-24_17 52 47](https://user-images.githubusercontent.com/42325138/88410409-a4cfd200-cdd6-11ea-8ee9-bc5a6ab2e8e6.png)
![2020-07-24_17 52 49](https://user-images.githubusercontent.com/42325138/88410411-a5686880-cdd6-11ea-8c67-0aee8b844ef1.png)
![2020-07-24_17 52 51](https://user-images.githubusercontent.com/42325138/88410412-a5686880-cdd6-11ea-939b-0184e4048dcf.png)

**Comment by democat3457** [comment]
Might be better to have a video for it? The screenshots are pretty non-explanatory.

**Comment by Titoo8899** [comment]
Hi,
okay I make a video about this Mods

**Comment by Titoo8899** [comment]
hi,
a Youtube mini Video from me with the Support Problem. I hope this Video help you to Support your mod with the FreeCamera Mod.
Link: https://www.youtube.com/watch?v=m5zgbH4JkDM

**Comment by PieKing1215** [comment]
Ok I see the problem now.
Will be fixed shortly

**Comment by Titoo8899** [comment]
hi,
thank you for the good news and I was so happy of your mod 👍

**Comment by PieKing1215** [comment]
Should be fixed in [v0.4.5](https://github.com/PieKing1215/InvMove/releases/tag/v0.4.5)

**Comment by Titoo8899** [comment]
Hi,
I have the new 1.12.2 Update 0.4.5 testet and it works fantastic the movements of FreeCamera Works and I have no Bugs found.
