### ISSUE TITLE
(1.15.2 | 0.4.6) JEI not showing, and got log on bottom showing error

### ISSUE THREAD

**Issue by dreckz** [PieKing1215/InvMove-Forge#5]
**Describe the bug**
Invmove is having a compatibility issue with JEI

**To Reproduce**
Have JEI and possibly JER installed with invmove and look at the inventory.  The JEI template does not show up.

**Crash Log**
The Log prints out an error in compatibility with JEI _(scroll to the bottom of the log to see)_
[2020-08-06-7.log](https://github.com/PieKing1215/InvMove/files/5038712/2020-08-06-7.log)

**Version and Mod List**
List the version of InvMove, the version of Forge, and the version of Minecraft the issue happens on:
InvMove: 0.4.6
Forge: 31.2.35
Minecraft: 1.15.2

**Comment by PieKing1215** [comment]
Can you attach a mod list or try to reproduce the problem with as few mods as you can?
I can't get this problem to happen with just InvMove, JEI, and JER.

It seems like the JEI runtime is failing to start for some reason and my code wasn't set up to deal with that.
If you can get it to happen with only a few mods it would make finding the problem much easier.

**Comment by PieKing1215** [comment]
If this is still an issue, feel free to reopen an issue in the new [rewrite repo](https://github.com/PieKing1215/InvMove).
