### ISSUE TITLE
License Issue: GLPv3 sadly isn't suited for Minecraft mods (LGPLv3?)

### ISSUE THREAD

**Issue by macbrayne** [PieKing1215/InvMove-Forge#8]
Just a heads up that there might be an issue with your license. I think you should be able to migrate easily as you're the only contributor and don't have to ask anybody for permission to change the license.

Possible solutions: Migrate to LGLPv3 or add a linking exception

(See the issue request for modrinth at https://github.com/modrinth/code/issues/1992 for a explanation)

**Comment by PieKing1215** [comment]
Oh, thanks for bringing this to my attention, I'll migrate my mods over to LGPLv3
