### ISSUE TITLE
Unable to Sprint in UIs

### ISSUE THREAD

**Issue by anabsolutesloth** [PieKing1215/InvMove-Forge#9]
**Describe the bug**
Cannot Sprint in UIs, opening an Inventory UI immediately stops sprinting, and i can't start sprinting in one.

**To Reproduce**
1. Install Invmove
2. Attempt to sprint in a UI.
3. Be immediately stopped from sprinting.

**Version and Mod List**
List the version of InvMove, the version of Forge, and the version of Minecraft the issue happens on:
InvMove: 0.4.6
Forge: 36.1.32
Minecraft: 1.16.5

List any other mods being used (other than Cloth Config):
Modlist of Valhelsia 3, with Tetra updated to 3.14.2
https://www.curseforge.com/minecraft/modpacks/valhelsia-3
Also tried in 1.16.4 with no mods other than Cloth config and Invmove, also failed to sprint.

**Comment by PieKing1215** [comment]
Should be fixed in the [rewrite](https://github.com/PieKing1215/InvMove), feel free to reopen an issue there if not.
